version: '2'
services:
    chrome:
        restart: always
        image: selenium/node-chrome:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        depends_on:
          - hub
        environment:
          HUB_HOST: hub
    hub:
        image: selenium/hub:3.14.0-gallium
        restart: always
    postgres:
        image: postgres
        restart: always
        # generate with python3 make-env.py
        env_file:
          - db.env
    redis:
        image: redis
    requeue-worker:
        build: .
        restart: always
        command: flask requeue-worker
        environment:
          - FLASK_APP=main
    screenshot-worker:
        build: .
        restart: always
        command: flask screenshot-worker
        volumes:
          - zonemonitor-screenshots:/app/static/screenshots
        environment:
          - FLASK_APP=main
    app:
        build: .
        restart: always
        volumes:
          - zonemonitor-db-versions:/app/migrations/versions
          - zonemonitor-screenshots:/app/static/screenshots
        env_file:
          - db.env
        ports:
          - "8088:80"
    certstream-server:
        image: certstream
        environment:
          - NOSSL=1
        restart: always
    certstream-feeder:
        build: feed/certstream
        restart: always
volumes:
    zonemonitor-db-versions:
    zonemonitor-screenshots:

